### ISSUE TITLE
Add support for Buckets without Properties/BucketName

### ISSUE THREAD

**Issue by otbe** [ar90n/serverless-s3-local#10]
Hi

I really like your project and tried to use it in a side project, but it wont work as expected. It seems that [your code](https://github.com/ar90n/serverless-s3-local/blob/master/index.js#L157) assumes that a bucket must have Properties and a BucketName and will throw otherwise (cannot read BucketName of undefined)

```yml
resources:
  Resources:
    SourceBucket:
      Type: AWS::S3::Bucket
```

I have forked this repo and added some checks and it works for me :)
If this is expected behavior please feel free to close this issue and decline my PR.

Thanks!
