### ISSUE TITLE
Functions are not working with latest dependencies

### ISSUE THREAD

**Issue by jjdechavez** [ar90n/serverless-s3-local#110]
Hello everyone, I'm still new on the serverless and aws development. I would like to ask that my functions are not working base on the serverless.yaml file

I already tried the examples on this repo which are working but there version seems outdated.

heres my package.json
```js
{
  "name": "test-s3-local",
  "version": "1.0.0",
  "description": "",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aws-sdk": "^2.802.0"
  },
  "devDependencies": {
    "serverless": "^2.14.0",
    "serverless-offline": "^6.8.0",
    "serverless-s3-local": "^0.6.7"
  }
}

```

serverless.yaml
```yaml
service: test-s3-local
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-s3-local
  - serverless-offline
custom:
  s3:
    host: localhost
    port: 8000
    directory: /tmp

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
        method: GET
        path: /

```
handler.js
```js
const AWS = require("aws-sdk");

module.exports.webhook = (event, context, callback) => {
  const S3 = new AWS.S3({
    s3ForcePathStyle: true,
    accessKeyId: "S3RVER", // This specific key is required when working offline
    secretAccessKey: "S3RVER",
    endpoint: new AWS.Endpoint("http://localhost:8000"),
  });
  S3.putObject(
    {
      Bucket: "local-bucket",
      Key: "1234",
      Body: new Buffer("abcd"),
    },
    () => {
      callback(null, "ok");
    }
  );
};

```

And run the server by `yarn sls offline start`
and gives me 
```
yarn run v1.22.4
$ /mnt/ExternalHDD/techmaker/learn/test-s3-local/node_modules/.bin/sls offline start
Serverless: Configuration warning at 'functions.webhook.events[0]': unsupported function event
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: starting handler
warn: the bucket "local-bucket" already exists
Serverless: S3 local started ( port:8000, family: IPv4, address: 127.0.0.1 )
offline: Starting Offline: dev/us-east-1.
offline: Offline [http for lambda] listening on http://localhost:3002
offline: Function names exposed for local invocation by aws-sdk:
           * webhook: test-s3-local-dev-webhook
```

Whenever I tried to call on localhost:3000 with curl
`curl localhost:3000`

which gives me `curl: (7) Failed to connect to localhost port 3000: Connection refused`

With the aws-cli which is working and got the field Etag
`aws --endpoint http://localhost:8000 s3api put-object --bucket local-bucket --key handler.js --body ./handler.js`
result was:
```
{
    "ETag": "\"8431e26efbd2bf78d262c8a1e02309e6\""
}
```

I hope someone help me. TIA
