### ISSUE TITLE
Using custom bucket configuration, the event handler doesn't match the bucket name

### ISSUE THREAD

**Issue by mbudm** [ar90n/serverless-s3-local#21]
Hi - me again. I  might be able to workaround this one by having a simpler config but it may be worth looking into.

With s3 events you can either have the bucket created by the event config for the triggered lambda or you can use [custom bucket configuration](https://serverless.com/framework/docs/providers/aws/events/s3#custom-bucket-configuration).

I'm using the latter, like this.

```yml
functions:
  uploaded:
    handler: fotos/uploaded.uploadedItem
    events:
      - s3: fotos
```

Then I add my custom bucket config in the resources section, changing the name to something a bit more realistic for an s3 bucket name (fotopia-web-app-prod):

```
    S3BucketFotos:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        AccessControl: PublicRead
```

My lambda wasnt firing when I PUT images into the bucket so I added some logging into ```serverless-s3-local``` like so:

![screen shot 2018-03-21 at 8 20 22 pm](https://user-images.githubusercontent.com/2467577/37702033-56e7ab28-2d45-11e8-94c7-a0d170b659fc.png)

Which revealed the problem - the event handler has the short (alias?) bucket name:

![screen shot 2018-03-21 at 8 10 15 pm](https://user-images.githubusercontent.com/2467577/37702072-7bcf2024-2d45-11e8-89ae-c7d194e2f5e8.png)

I'll have a dig around perhaps theres a way via the sls plugin API to get the connection between the shorthand name and the longer name specified in resources.
