### ISSUE TITLE
S3-local doesn't pass in function-specific environment variables when triggered

### ISSUE THREAD

**Issue by footballencarta** [ar90n/serverless-s3-local#25]
When using this project to test S3 uploads, any specific environment variables set for a function aren't passed in when triggered from a local S3 upload. See below yml fragment:

```
emailUploaded:
  handler: handler.handle
  environment:
    command: email:uploaded
  events:
    - s3: bucket-name
```
The command variable isn't available when the function is ran from the local S3 trigger.
