### ISSUE TITLE
Support for S3:Events Prefix and Suffix Rules

### ISSUE THREAD

**Issue by malcyL** [ar90n/serverless-s3-local#27]
Serverless allows for the setting of prefix and suffix rules on S3 Events:

https://serverless.com/framework/docs/providers/aws/events/s3#setting-filter-rules

```
functions:
  users:
    handler: incoming.handler
    events:
      - s3:
          bucket: mybucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
            - suffix: .zip
```

I think serverless-s3-local is ignoring these rules?

My use case is an existing system which changes the key of a file after it's completed processing. For example, a file is uploaded to s3 with a bucket and key: ```s3://mybucket/incoming/file1.zip``` and then after processing it is moved to ```s3://mybucket/processed/file1.zip```.

When running locally with serverless-s3-local the handler is triggered twice, once when it is initially created and again when the key is changed. When deployed to AWS this doesn't happen as the prefix and suffix rules are applied.
