### ISSUE TITLE
I'm in port hell! 

### ISSUE THREAD

**Issue by appernetic** [ar90n/serverless-s3-local#35]
I have set s3 local on port 9000. But still serverless says it's in use:

Serverless: Offline listening on http://localhost:3000
2018-07-24 21:45:51.438:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:8000: java.net.BindException: Address already in use
java.net.BindException: Address already in use

I have DynamoDB on port 8000, Lambda local on port 4000, Reactjs on port 3000.

This is my custom secton in serverless.yml:

```
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # Load our webpack config
  webpackIncludeModules: true # enable auto including node_modules
  graphiql:
    babelOptions:
      presets: [es2015, es2016, stage-0]
      plugins: [transform-runtime]
  serverless-offline:
    babelOptions:
      presets: [es2015, es2016, stage-0]
      plugins: [transform-runtime]
  dynamodb:
   start:
      migrate: true
  s3:
    host: 0.0.0.0
    port: 9000
    directory: /tmp
    # Uncomment the first line only if you want to use cors with specified policy
    # Uncomment the second line only if you don't want to use cors
    # Not uncomment the these lines only if your wanto use cors with default policy
    # cors: relative/path/to/your/cors/policy/xml
    # cors: false
    # Uncomment only if you already have a S3 server running locally
    # noStart: true
```
