### ISSUE TITLE
Issue starting the application with serverless-s3-local plugin

### ISSUE THREAD

**Issue by sohailalam2** [ar90n/serverless-s3-local#37]
Lately I have been facing this issue with the serverless-s3-local plugin. Any idea what I am doing wrong here?

```
  Type Error ---------------------------------------------
 
  this.client.s3Event.map is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: this.client.s3Event.map is not a function
    at Promise (D:\workspace\node_modules\serverless-s3-local\index.js:139:27)
    at new Promise (<anonymous>)
    at ServerlessS3Local.startHandler (D:\workspace\node_modules\serverless-s3-local\index.js:103:12)
    at BbPromise.reduce (D:\workspace\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at Watching.compiler.watch [as handler] (D:\workspace\node_modules\serverless-webpack\lib\wpwatch.js:67:11)
    at compiler.hooks.done.callAsync (D:\workspace\node_modules\webpack\lib\Watching.js:100:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\workspace\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\workspace\node_modules\tapable\lib\Hook.js:35:21)
    at Watching._done (D:\workspace\node_modules\webpack\lib\Watching.js:99:28)
    at compiler.emitRecords.err (D:\workspace\node_modules\webpack\lib\Watching.js:73:19)
    at Compiler.emitRecords (D:\workspace\node_modules\webpack\lib\Compiler.js:372:39)
    at compiler.emitAssets.err (D:\workspace\node_modules\webpack\lib\Watching.js:54:20)
    at hooks.afterEmit.callAsync.err (D:\workspace\node_modules\webpack\lib\Compiler.js:358:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\workspace\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\workspace\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (D:\workspace\node_modules\webpack\lib\Compiler.js:355:27)
    at done (D:\workspace\node_modules\neo-async\async.js:2854:11)
    at D:\workspace\node_modules\neo-async\async.js:2805:7
    at D:\workspace\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
    at PluginManager.invoke (D:\workspace\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (D:\workspace\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (D:\workspace\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Serverless.run (D:\workspace\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (D:\workspace\node_modules\serverless\bin\serverless:43:50)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           9.3.0
     Serverless Version:     1.29.2
```

Here is my serverless.yml config

```yaml
service: my-api

# ---------------------------------------
#            Custom Configs
# ---------------------------------------

custom:
  defaultStage: qa # Possible Values: qa, beta and prod
  defaultRegion: eu-central-1
  defaultBucket: my.uploads
  # webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  s3:
    bucketName: ${self:custom.defaultBucket}
    host: 0.0.0.0
    port: 9000
    directory: ./s3-local
    cors: false
  serverless-offline:
    port: 8080

# ---------------------------------------
#               Providers
# ---------------------------------------

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  timeout: 120
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  environment:
    AWS_DEPLOYMENT_REGION: ${self:provider.region}
    AWS_DEPLOYMENT_STAGE: ${self:provider.stage}
    AWS_DEFAULT_BUCKET_NAME: ${self:custom.defaultBucket}
  # IAM Roles
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.s3.bucketName}/*"

# ---------------------------------------
#             Lambda Functions
# ---------------------------------------

functions:
  status:
    handler: src/modules/status/handler.handle
    events:
      - http:
          path: /status
          method: any
          cors: true	  
# ---------------------------------------
#            Plugins
# ---------------------------------------

plugins:
  - serverless-webpack
  - serverless-express
  - serverless-s3-local
  - serverless-offline

# ---------------------------------------
#             Resources
# ---------------------------------------

resources:
  Resources:
    # ---------------------------------------
    #             S3 Buckets
    # ---------------------------------------
    S3CoursesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3.bucketName}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
          - AllowedOrigins:
              - "*"
          - AllowedHeaders:
              - "*"
```

**Comment by ar90n** [comment]
Hi @sohailalam2 
Thanks for you report. But I couldn't reproduce your trouble in my environment (osx). Does this issue occur in example projects ?

**Comment by ken0x0a** [comment]
same error here >_<

I tried to find reason about 1 hour I think
Thank you for great plugin by the way.

```
```
```
service:
  name: cdn-s3

frameworkVersion: "=1.29.2"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-s3-local
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  profile: ${self:custom.profiles.${self:provider.stage}}
  stage: ${opt:stage, self:custom.defaultStage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

```
 log

```
Serverless: Bundling with Webpack...
Time: 5467ms
Built at: 08/02/2018 3:00:59 AM
         Asset     Size   Chunks             Chunk Names
    handler.js  132 KiB  handler  [emitted]  handler
handler.js.map  148 KiB  handler  [emitted]  handler
Entrypoint handler = handler.js handler.js.map
[./handler.ts] 1.64 KiB {handler} [built]
[./node_modules/buffer-from/index.js] 1.56 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/array-set.js] 3.12 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/base64-vlq.js] 4.6 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/binary-search.js] 4.15 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js] 39.6 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/source-map-generator.js] 14 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/source-node.js] 13.5 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/source-map.js] 405 bytes {handler} [built]
[./node_modules/source-map-support/source-map-support.js] 17.1 KiB {handler} [built]
[./source-map-install.js] 41 bytes {handler} [built]
[fs] external "fs" 42 bytes {handler} [optional] [built]
[0] multi ./source-map-install.js ./handler.ts 40 bytes {handler} [built]
[module] external "module" 42 bytes {handler} [optional] [built]
[path] external "path" 42 bytes {handler} [built]
    + 4 hidden modules
Serverless: Watching for changes...
S3 local started ( port:8040 )
Serverless: creating bucket: ___

  Type Error ---------------------------------------------

  this.client.s3Event.map is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.7.0
     Serverless Version:     1.29.2
```

**Comment by ken0x0a** [comment]
same error here >_<

Thank you for great plugin by the way.

```
 s3Event:
   Subject {
     _isScalar: false,
     observers: [],
     closed: false,
     isStopped: false,
     hasError: false,
     thrownError: null },
```

```
service:
  name: cdn-s3

frameworkVersion: "=1.29.2"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-s3-local
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  profile: ${self:custom.profiles.${self:provider.stage}}
  stage: ${opt:stage, self:custom.defaultStage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

```
 log

```
Serverless: Bundling with Webpack...
Time: 5467ms
Built at: 08/02/2018 3:00:59 AM
         Asset     Size   Chunks             Chunk Names
    handler.js  132 KiB  handler  [emitted]  handler
handler.js.map  148 KiB  handler  [emitted]  handler
Entrypoint handler = handler.js handler.js.map
[./handler.ts] 1.64 KiB {handler} [built]
[./node_modules/buffer-from/index.js] 1.56 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/array-set.js] 3.12 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/base64-vlq.js] 4.6 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/binary-search.js] 4.15 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js] 39.6 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/source-map-generator.js] 14 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/lib/source-node.js] 13.5 KiB {handler} [built]
[./node_modules/source-map-support/node_modules/source-map/source-map.js] 405 bytes {handler} [built]
[./node_modules/source-map-support/source-map-support.js] 17.1 KiB {handler} [built]
[./source-map-install.js] 41 bytes {handler} [built]
[fs] external "fs" 42 bytes {handler} [optional] [built]
[0] multi ./source-map-install.js ./handler.ts 40 bytes {handler} [built]
[module] external "module" 42 bytes {handler} [optional] [built]
[path] external "path" 42 bytes {handler} [built]
    + 4 hidden modules
Serverless: Watching for changes...
S3 local started ( port:8040 )
Serverless: creating bucket: ___

  Type Error ---------------------------------------------

  this.client.s3Event.map is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.7.0
     Serverless Version:     1.29.2
```
