### ISSUE TITLE
Integration with webpack and s3-local

### ISSUE THREAD

**Issue by Goues** [ar90n/serverless-s3-local#40]
Hi,

I'm currently developing a serverless application using serverless-webpack and serverless-s3-local in development. When I change my code, webpack automatically updates lambda functions but not those that are triggered by s3 events.

```
functions:
  Worker1:
    handler: src/handlers/Worker1.handler
    events:
      - http:
          method: GET
          path: /worker
  Worker2:
    handler: src/handlers/Worker2.handler
    events:
      - s3:
          bucket: my-bucket
          event: s3:ObjectCreated:*
```

Worker1 puts files to s3 and Worker2 should do stuff with them, but in watch mode, only Worker1 is updated, Worker2 stays unchanged. Using `SLS_DEBUG`, I can confirm that webpack does its job and does bundle the function.

I think there are missing hooks in s3-local for webpack when handling events so that s3 event callbacks point to the functions they were first created with.

~~I do not feel qualified to submit a PR, but if I get a little help with it, I'll try to do so. This is my first project in serverless.~~ I've actually managed to make a PR.

Thank you
