### ISSUE TITLE
Issue at startup

### ISSUE THREAD

**Issue by kkogovsek** [ar90n/serverless-s3-local#47]
Hey I just tried to load local-s3 and I get startup error:
```
client s3event object
S3 local started ( port:4001 )
WARN: No buckets found to create
error: [S3rver] uncaughtException: Cannot read property 'then' of null date=Tue Sep 11 2018 12:34:41 GMT+0200 (Cent
ral European Summer Time), pid=14708, uid=501, gid=20, cwd=/Users/klemenk/work/tt37.com/client-app, execPath=/Users
/klemenk/.nvm/versions/node/v10.9.0/bin/node, version=v10.9.0, argv=[/Users/klemenk/.nvm/versions/node/v10.9.0/bin/
node, /Users/klemenk/.nvm/versions/node/v10.9.0/bin/sls, offline, start, --dontPrintOutput], rss=112562176, heapTot
al=84844544, heapUsed=54042744, external=697365, loadavg=[1.44677734375, 1.97412109375, 2.05126953125], uptime=9130
6
TypeError: Cannot read property 'then' of null
    at client.S3rver.run (/Users/klemenk/work/tt37.com/client-app/node_modules/serverless-s3-local/index.js:196:29)
    at Server.server.listen.err (/Users/klemenk/work/tt37.com/client-app/node_modules/s3rver/lib/index.js:36:9)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at Server.EventEmitter.emit (domain.js:442:20)
    at emitListeningNT (net.js:1368:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
My config looks like:
```
service: tt37com

plugins:
  - serverless-offline
  - serverless-s3-local

provider:
  name: aws
  runtime: nodejs8.10

functions:

  deployWebsite:
    handler: lambdas/deployWebsite.lambdaHandler
    memorySize: 512
    timeout: 60
    events:
      - http:
          path: deployWebsite
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:*
        Resource: "*"

custom:
  serverless-offline:
    port: 4000
    resourceRoutes: true
  s3:
    host: 0.0.0.0
    port: 4001
    directory: /tmp
```

My environment:
- OS: osx high sierra
- Node version: 10.9

**Comment by kkogovsek** [comment]
I tried using node 8.10 with no success.

**Comment by kkogovsek** [comment]
Turns out i didn't setup resources:
```
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
```

works now, sorry for bothering
