### ISSUE TITLE
Where can I see uploaded files?

### ISSUE THREAD

**Issue by SirwanAfifi** [ar90n/serverless-s3-local#48]
Hi, thanks for sharing :) 

I installed this package, Here's the settings inside `server.yml`:

```
service: myProject

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-plugin-typescript
  - serverless-s3-local
  - serverless-offline

custom:
  s3:
    port: 8000
    directory: /tmp
    cors: false
    # Uncomment only if you already have a S3 server running locally
    # noStart: true

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket

functions:
  s3hook:
    handler: server.uploadFile
    events:
      - http:
          path: uploadFile
          method: post
      - s3: local-bucket
```

As you see I defined a handler called `s3hook` which exposes an URL to upload a file. Here's the also the handler inside a file called `server.ts`:

```
import * as awsServerlessExpress from "aws-serverless-express";
exports.uploadFile = async (event, context) => {
  awsServerlessExpress.proxy(server, event, context);
};
```

Which uses `aws-serverless-express` to proxy requests and send the requests to express server, the express implementation is inside a file called `app.ts`:

```
import * as express from "express";
import * as AWS from "aws-sdk";
import * as uuid from "uuid";

const app = express();

const S3 = new AWS.S3({
  s3ForcePathStyle: true,
  endpoint: "http://localhost:8000"
});
app.post("/uploadFile", (_, respose) => {
  const params = _.body;
  const fileName = uuid.v4();

  S3.putObject(
    {
      Bucket: "local-bucket",
      Key: fileName,
      Body: params
    },
    () => {
      respose.send("Uploaded");
    }
  );
});

export { app };
```

at this point I can use something like `curl` to post a file:

```
curl -X POST \
  http://localhost:3000/uploadFile \
  --data @myFile.jpg
```

After posting the file I can see the "Uploaded" message in the response. But the problem is that I can't see uploaded file inside `/temp folder` it's empty:

![image](https://user-images.githubusercontent.com/5256416/46217495-00ea7c00-c34f-11e8-90d9-d238c669cf5d.png)

Any idea?
