### ISSUE TITLE
Custom s3 configuration bucket names not supported

### ISSUE THREAD

**Issue by mbruning24** [ar90n/serverless-s3-local#515]
I have a serverless configuration that uses the v3 custom bucket configuration for s3 events shown [here](https://www.serverless.com/framework/docs/providers/aws/events/s3#custom-bucket-configuration).

```
provider:
  s3:
    myBucket:
      name: 'some-custom-name-here'
      # etc...

functions:
  myFunction:
    events:
      - s3:
          bucket: myBucket
          event: s3:ObjectCreated:*
```

When the `buckets()` function is called in the start handler ([here](https://github.com/ar90n/serverless-s3-local/blob/master/serverless-s3-local/index.js#L543)) to create the resources for s3rver, it just returns the string `myBucket` as the bucket name, which obviously in this case it is not.

Can we get some additional logic to check for bucket configurations at `this.service.provider.s3[key]` before just defaulting to the identifier?
