### ISSUE TITLE
Deploy issue: "<bucketname> already exists in stack"

### ISSUE THREAD

**Issue by bresheske** [ar90n/serverless-s3-local#53]
**Main Issue:** When running severless-s3-local locally, the plugin will scan the resources section of the serverless.yml file to find buckets to create.  However, when "sls deploy" is executed, serverless will scan not only the resources section, but also the functions/events section as well.  Serverless will create an s3 bucket for each it finds.

So - the example found [here](https://github.com/ar90n/serverless-s3-local/blob/master/example/simple_event/serverless.yml) will not deploy with serverless, as it will attempt to create "local-bucket" twice, and will fail doing so.  Here's the lines in question:

```
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket   <-- creates 'local-bucket'
functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          method: GET
  s3hook:
    handler: handler.s3hook
    events:
      - s3: local-bucket    <-- creates 'local-bucket' again.
```

**Work-around**: Currently I need to comment-out the resources section while deploying, and un-comment it when running locally.  

**Proposed Solution**: serverless-s3-local should treat the events and resources the same way as serverless deploy will, and also create local buckets when they are found in the functions/events section.

**Dependencies in package.json**:

```
  "devDependencies": {
    "@types/node": "^10.12.18",
    "concurrently": "^4.1.0",
    "parcel-bundler": "^1.11.0",
    "serverless": "^1.35.1",
    "serverless-offline": "^3.31.3",
    "serverless-s3-local": "^0.3.20",
    "typescript": "^3.2.2"
  },
  "dependencies": {
    "aws-sdk": "^2.382.0"
  }
```

**Comment by bresheske** [comment]
After digging into the source, I see that serverless-offline-local allows for a --buckets <bucketname> option, which serves as a better work-around.

**Comment by bresheske** [comment]
@ar90n No problem at all.  Thanks for creating the plugin!

**Comment by ar90n** [comment]
I fixed this issue at v0.3.21. Please try it!

**Comment by bresheske** [comment]
@ar90n Thanks very much! I'll give this a try and get back to you a bit later today.

**Comment by bresheske** [comment]
@ar90n I think we're all good!  Looks like the plugin will create local buckets for both functions/events as well as resources.  

I think we can close this item as resolved.  Thanks!

**Comment by ar90n** [comment]
@bresheske It is good news for me. If you meet some issue, please don't hesitate to let me know ! Thanks for your all contribution.

**Comment by sudosoul** [comment]
I'm still having this issue on 0.4.4 during deploy

```
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
```

```
  Serverless Error ---------------------------------------
 
  An error occurred: NewResource - local-bucket already exists.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           8.16.0
     Serverless Version:     1.42.2
```

**Comment by ar90n** [comment]
Hi @sudosoul 
In the deploying case, BucketName must be unique over all regions. So if anyone have already created a bucket whose name is local-bucket,  We meet the above error.
I tried to deploy simple project with unique BucketName. 

```
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ar90n-ar90n-ar90n-local-bucket
```

And I got the following.
```
$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service serverless-s3-local-example.zip file to S3 (23.64 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......................

.......
Serverless: Stack update finished...
Service Information
service: serverless-s3-local-example
stage: dev
region: us-east-1
stack: serverless-s3-local-example-dev
resources: 10
api keys:
  None
endpoints:
  GET - https://7szjwbzszl.execute-api.us-east-1.amazonaws.com/dev/
functions:
  webhook: serverless-s3-local-example-dev-webhook
layers:
  None
Serverless: Removing old service artifacts from S3...
```
