### ISSUE TITLE
Supplied credentials being ignored

### ISSUE THREAD

**Issue by brdly-smith** [ar90n/serverless-s3-local#561]
The documentation says that the access keys can be overridden like this:

```yml
custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 6000
    lambdaPort: 4321
  s3:
    address: 0.0.0.0
    port: 4569
    directory: /tmp
    accessKeyId: access
    secretAccessKey: test
```

But no matter what, the server uses the default `S3RVER` values.
