### ISSUE TITLE
s3rver requires static website config to be xml

### ISSUE THREAD

**Issue by bixelsnl** [ar90n/serverless-s3-local#61]
https://github.com/jamhall/s3rver/blob/master/lib/s3rver.js#L92

Same idea as https://github.com/ar90n/serverless-s3-local/issues/20 I think

**Comment by ar90n** [comment]
HI @bixelsnl 
Thanks for your comment. It is exactly right. I implemented this feature by the way you suggested. If you try this feature, please use v0.4.3 and specify the path to website.xml by the following.

```
custom:
  s3:
    host: 0.0.0.0
    port: 8000
    directory: /tmp
    website: relative/path/to/your/website.xml
```
