### ISSUE TITLE
ERR_INVALID_ARG_TYPE when trying to upload file

### ISSUE THREAD

**Issue by bartvollebregt** [ar90n/serverless-s3-local#62]
I have a setup with an additionalStacks S3 bucket:
```
custom:
  additionalStacks:
    permanent:
      Resources:
        S3BucketData:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: my-local-bucket
  s3:
    host: 0.0.0.0
    port: 8000
    directory: ./buckets/
  webpack:
    keepOutputDirectory: true
    includeModules: false
    packager: 'yarn'
```

When I try to upload a file to my bucket I get an error.
```
 aws --endpoint http://localhost:8000 s3api put-object --bucket my-local-bucket --key test/test1.txt --body ./test/test1.txt
```

Error:
```
info: PUT /my-local-bucket/test/test1.txt 500 1ms -

  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
      at Function.from (buffer.js:208:11)
      at authentication (~/IdeaProjects/my-project/lambda/node_modules/s3rver/lib/middleware/authentication.js:182:37)
      at dispatch (~/IdeaProjects/my-project/lambda/node_modules/koa/node_modules/koa-compose/index.js:42:32)
      at website (~/IdeaProjects/my-project/lambda/node_modules/s3rver/lib/middleware/website.js:47:14)

```
