### ISSUE TITLE
Accessing s3-local from within a docker container

### ISSUE THREAD

**Issue by PierrickI3** [ar90n/serverless-s3-local#699]
Hi,

I am trying to access my serverless-s3-local instance running on port 9002 from within a Docker container using this code:

```python
def put_s3_bucket(bucket, accessid, data):
  s3 = boto3.resource('s3', region_name=os.environ['AWS_REGION'], endpoint_url='http://host.docker.internal:9002') # call parent endpoint
  s3.Object(bucket, 'accounts/' + accessid + '/' + str(uuid.uuid4())).put(Body=data)
```

I get this error:
`botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist`

According to the log, it seems to be connecting fine:
```
2023-03-21 16:31:25,051:DEBUG:urllib3.connectionpool:connectionpool.py:232:_new_conn Starting new HTTP connection (1): host.docker.internal:9002
2023-03-21 16:31:25,085:DEBUG:urllib3.connectionpool:connectionpool.py:465:_make_request http://host.docker.internal:9002 "PUT /dev-finance-storage-cmb/accounts/82d95aca-14c3-4117-bd59-917a45e69a77/d3089d37-5137-4f48-acde-c0e91db0ef48 HTTP/1.1" 404 178
```

I also see this on my local machine (where s3-local is running):

```
error: No bucket found for "host.docker.internal"

info: finance-storage-cmb/accounts/82d95aca-14c3-4117-bd59-917a45e69a77/d3089d37-5137-4f48-acde-c0e91db0ef48 404 17ms -
```

Docker using the `network=host` parameter to use the host's network.
I tried other parameters but no luck so far.

Why is it using `host.docker.internal` as the host name?

Thanks

**Comment by ar90n** [comment]
Hi @PierrickI3 

> Why is it using `host.docker.internal` as the host name?

As you mentioned avobe, endpoint_url is specified as 'http://host.docker.internal:9002`. So `host.docker.internal` is used as the host anme of S3.

To solve this issue, could you share the followings ?

* The concrete value of bucket which is an argument of put_s3_bucket 
* serverless.yml

Thanks !

**Comment by PierrickI3** [comment]
Sure thing. 

* Concrete value: a regular object such as:

```json
{
  "values": 
    [
      {
        "vendorAccountId": "0AZRPXKDLT", 
        "label": "COMPTE PRINCIPAL XXXX", 
        "balance": "1541.44", 
        "iban": null, 
        "currency": "EUR", 
        "type": 1
      }, 
      {
        "vendorAccountId": "TD44474443", 
        "label": "COMPTE JOINT XXXXXXXX", 
        "balance": "332.69", 
        "iban": null, 
        "currency": "EUR", 
        "type": 1
      }, 
(truncated...)
```

serverless.yml:

```yaml
serverless.yml:
service: finance-woob
app: finance
custom:
  s3:
    host: localhost
    directory: ../../../s3-local
    port: 10302
  packageExternal:
    external:
      - ../../libs/aws-lib.js
      - ../../libs/aws-sdk.js
      - ../../libs/dynamodb-lib.js
      - ../../libs/response-lib.js
      - ../../libs/request-lib.js
      - ../../libs/s3-lib.js
  serverless-offline:
    httpPort: 4000
    useChildProcesses: true
  prune:
    automatic: true
    number: 1
  cors-config:
    origins:
      - '*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - contextid
      - access-control-allow-origin
      - access-control-allow-methods
      - access-control-allow-headers
      - cache-control
      - expires
      - pragma
    allowCredentials: false
provider:
  name: aws
  runtime: nodejs14.x
  profile: finance
  stage: dev
  region: eu-central-1
  deploymentBucket: my.${self:provider.stage}.finance.serverless.deploys
  versionFunctions: false
  tracing:
    lambda: true
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: Allow
      Action:
        - ecs:RunTask
      Resource: '*'
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: '*'
  timeout: 29 # If using web sockets, you can increase this. It will cause a warning when running 'serverless deploy' but you can ignore it.
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${opt:stage, self:provider.stage}-FinanceGW-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${opt:stage, self:provider.stage}-FinanceGW-rootResourceId
functions:
  getAccounts:
    handler: handler.getAccounts
    events:
      - http:
          path: woob/accounts
          method: get
          cors: ${self:custom.cors-config}
  getOperations:
    handler: handler.getOperations
    events:
      - http:
          path: woob/accesses/{accessId}/operations
          method: get
          cors: ${self:custom.cors-config}

resources:
  Resources:
    CMBStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${opt:stage, self:provider.stage}-finance-storage-cmb

package:
  patterns:
    - '!.dynamodb/**'
    - '!.nyc_output/**'
    - '!coverage/**'
    - '!test/**'
    - '!.git/**'
    - '!serverless.yml'
    - '!.serverless/**'
    - '!requests.http'
    - '!files/**'

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-common-excludes
  - serverless-package-external

```
