### ISSUE TITLE
serverless.yaml example returns an error when includeing s3:event.

### ISSUE THREAD

**Issue by your-eminence** [ar90n/serverless-s3-local#721]
The example serverless.yaml in the readme provides:
```
  s3hook:
    handler: handler.s3hook
    events:
      - s3: local-bucket
        event: s3:*
```

Which gives the following error when used:
```
Warning: Invalid configuration encountered
  at 'functions.index.events.0': unrecognized property 'event'
```

The only way I could get the event line to work was to use the following notation:

```
  s3hook:
    handler: handler.s3hook
    events:
      - s3:
          bucket: local-bucket
          event: s3:*
```
