### ISSUE TITLE
Support for S3:Events Prefix and Suffix Rules

### ISSUE THREAD

**Issue by fffan64** [ar90n/serverless-s3-local#93]
Please see
https://github.com/ar90n/serverless-s3-local/issues/27#issue-329025142

same problem in latest version 0.5.4
trigger all the time, ignore the rules filter

thanks !

**Comment by aklein-dex** [comment]
Same issue for me.
serverless-s3-local version: 0.4.4

$ sls --version
Framework Core: 1.66.0
Plugin: 3.5.0
SDK: 2.3.0
Components: 2.22.3

https://serverless.com/framework/docs/providers/aws/events/s3#setting-filter-rules
Despite the suffix is .jpg, if I add a file test.txt, it triggers the lambda.

**Comment by ar90n** [comment]
Thanks for your reports. 
But I couldn't reproduce this issue.
I guess this issue was caused by not catching up on the latest version of serverless and serverless-offline.
So I published a new version of serverless-s3-local to catch up on them.
Could you try it?

**Comment by fffan64** [comment]
thank you but same, i updated everything:

    "serverless": "^1.68.0",
    "serverless-offline": "^6.1.4",
    "serverless-s3-local": "^0.6.0",

i can see this log if it can help

```
starting handler
Serverless: Found S3 event listener for mybucket
[
  {
    name: 'mybucket',
    pattern: '.*',
    rules: [],
    func: [Function: func]
  }
]
warn: the bucket "mybucket" already exists
S3 local started ( port:8000, family: IPv4, address: 127.0.0.1 )
Serverless: creating bucket: mybucket
error: Error creating bucket. Bucket "mybucket" already exists
info: PUT /mybucket 409 6ms -
```

**Comment by ar90n** [comment]
Umm...
It seems that there are no problems.
This error is caused by a bucket whose name is same already existing.
But this bucket works correctly.

If you don't mind, could you share your serverless.yml or essential part of it.
I want to reproduce this issue in my environment.
Or please try to run the [resize_image example](https://github.com/ar90n/serverless-s3-local/tree/master/example/resize_image). I guess this example is similar to your product.

**Comment by fffan64** [comment]
ok, i found the mistake :/

i was declaring like that (WRONG)
```
events:
      - s3: ${self:custom.s3_bucket}
        event: s3:ObjectCreated:*
        rules:
          - prefix: ${self:custom.s3_key_base_input}
          - suffix: .zip
```

intead of (GOOD)
```
events:
      - s3: 
          bucket: ${self:custom.s3_bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.s3_key_base_input}
            - suffix: .zip
```

sorry for the trouble, though i was sure it worked on real s3...
