### ISSUE TITLE
TypeError: bucketName.charAt is not a function

### ISSUE THREAD

**Issue by itsmepetrov** [ar90n/serverless-s3-local#948]
In our project we specify buckets via Ref:

```yaml
events:
  - s3:
      existing: true
      bucket: !Ref IndexBucket
      rules:
        - prefix: data/batch/
```

unfortunately it breaks `getResource ForBucket` function:

```
error - unhandledRejection: TypeError: bucketName.charAt is not a function
    at ServerlessS3Local.getResourceForBucket (.../node_modules/serverless-s3-local/index.js:509:8)
```

I've created PR that resoles the issue: #947
