### ISSUE TITLE
An error occurred: <BUCKET NAME> already exists in stack arn:aws:cloudformation:us-east-1:996242555412 ...

### ISSUE THREAD

**Issue by igoralves1** [ar90n/serverless-s3-local#952]
I am using MAC chip Apple M3 Pro, macOS smona 146.1.

Following the instructions in https://github.com/ar90n/serverless-s3-local and when I run `sls dev --debug` Im getting the following error:

```
✖ An error occurred: S3Bucket052a36f5fb9elocalbucketz - 052a36f5fb9elocalbucketz already exists in stack arn:aws:cloudformation:us-east-1:996242555412:stack/ft-dev/5a21d0b0-5bf7-11ef-9e25-0affefb4c111.
ServerlessError2: An error occurred: S3Bucket052a36f5fb9elocalbucketz - 052a36f5fb9elocalbucketz already exists in stack arn:aws:cloudformation:us-east-1:996242555412:stack/ft-dev/5a21d0b0-5bf7-11ef-9e25-0affefb4c111.
    at <anonymous> (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/plugins/aws/lib/monitor-stack.js:168:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AwsDeploy.update (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/plugins/aws/lib/update-stack.js:166:5)
    at aws:deploy:deploy:updateStack (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/plugins/aws/deploy/index.js:206:9)
    at PluginManager.runHooks (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/classes/plugin-manager.js:680:9)
    at PluginManager.invoke (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/classes/plugin-manager.js:719:9)
    at PluginManager.spawn (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/classes/plugin-manager.js:740:5)
    at PluginManager.runHooks (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/classes/plugin-manager.js:680:9)
    at PluginManager.invoke (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/classes/plugin-manager.js:719:9)
    at PluginManager.spawn (/Users/ialves/.serverless/releases/4.2.4/serverless/lib/classes/plugin-manager.js:740:5)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/
```

The serverless is basically the same one of the tutorial:

```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: igoralves1
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ftest
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ft

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

custom:
  s3:
    host: localhost
    port: 8000
    directory: /tmp

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 052a36f5fb9elocalbucketz


functions:
  hello:
    handler: handler.hello

  testapi:
    handler: testapi.testapi
    events:
      - httpApi:
          method: POST
          path: /testapi

  webhook:
    handler: handler.webhook
    events:
      - http:
        method: GET
        path: /
  s3hook:
    handler: handler.s3hook
    events:
      - s3: 052a36f5fb9elocalbucketz
        event: s3:*

```
How to solve this issue?
From where is comming this account number `996242555412` in the error?
